apiVersion: v1
kind: Service
metadata:
  name: monitoring-operator-service
  namespace: monitoring
spec:
  ports:
  - name: http
    port: 443
    targetPort: 9443
  - name: web
    port: 8080
    targetPort: 8080
  selector:
    app: monitoring-operator


