name: checkout
on:
  push:
    tags:
      - v*
    branches:
      - master
      - main
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - uses: actions/checkout@v3
      - name: test
        run: go test -v ./...
      - name: golangci-lint
        run: curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b . latest
      - name: Lint
        run: ./golangci-lint run ./...
#        uses: golangci/golangci-lint-action@v3
#        with:
#          version: v1.50.0
          #args: -c .golangci.yml